# Generated by Django 2.2.17 on 2020-11-04 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio_envio', models.IntegerField()),
                ('codigo_envio', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
                ('dibujo', models.CharField(max_length=200)),
                ('diseño_especial', models.BooleanField(default=False)),
                ('precio_venta', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='imagenes_kalimbas')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Envio')),
            ],
        ),
    ]
