# Generated by Django 3.1.1 on 2020-11-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
                ('dibujo', models.CharField(max_length=200)),
                ('diseño_especial', models.BooleanField(default=False)),
                ('precio_venta', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='imagenes_kalimbas')),
            ],
        ),
    ]
